> NEI <- readRDS("exdata_data_NEI_data/summarySCC_PM25.rds")
> SCC <- readRDS("exdata_data_NEI_data/Source_Classification_Code.rds")
> maryland <- subset(NEI, fips == "24510")
> maryyear <- tapply(maryland$Emissions, maryland$year, sum)
> barplot(maryyear, xlab = "Year", ylab = "Total Emission ", main = "Total Emission per year in Baltimore")